### ISSUE TITLE
Make archive text configurable

### ISSUE THREAD

**Issue by rumpelsepp** [irrationalistic/atom-tasks#27]
I am suffering from this atom issue: https://github.com/atom/atom/issues/6435, https://github.com/atom/atom/issues/6214

I have already managed to find fonts which are able to display the ☐, ✔, ✘ characters. Since you can redefine these symbols (e.g. `[ ]`, `[x]`, `[-]`) in the settings, it is not a big deal to make atom-tasks work; even if there is no proper font available. 

It would be nice if the archive text is configurable as well: https://github.com/irrationalistic/atom-tasks/blob/master/lib/tasks.coffee#L320-L326

It is quite annoying in atom on linux:

![screenshot from 2015-06-15 14-40-19](https://cloud.githubusercontent.com/assets/1961699/8160022/76688a62-136c-11e5-999a-cc98ae669288.png)

**Comment by rumpelsepp** [comment]
Or maybe just use

```
"""
----------------------------
Archive:
"""
```

**Comment by irrationalistic** [comment]
I've added a setting to the package so you can control this to be whatever you want!

If you want to replace the existing one, you have to delete it first, then re-archive since it won't replace existing archive sections.

**Comment by rumpelsepp** [comment]
Nice! Thank you very much!
