### ISSUE TITLE
Customization suggestion: allow changing the 'tag' character

### ISSUE THREAD

**Issue by mangecoeur** [irrationalistic/atom-tasks#30]
Just thinking it would be handy to allow changing the 'tag' character from @ to whatever you want (I copy-paste tasks between text and Wunderlist which uses # ) just like you can change the 'task' character etc

**Comment by irrationalistic** [comment]
This would take a bit of refactoring, so I'll take a look and see what I can do!

**Comment by irrationalistic** [comment]
This should be implemented with v2.2.0 (commit f6960e22f76831e80931e3f1403827611af16a90).
