### ISSUE TITLE
Render as Markdown

### ISSUE THREAD

**Issue by Ridermansb** [irrationalistic/atom-tasks#31]
It would be nice to render markdown styles, at least the basics like links, bold ...

**Comment by irrationalistic** [comment]
In normal text, being able to see the `*test*` render as italic, for instance?

**Comment by Ridermansb** [comment]
Text with `*` are display in regular text.

No one formatation is displayed.

**Comment by irrationalistic** [comment]
The goal would be to see it formatted as if it was in a markdown file, though, right?

**Comment by Ridermansb** [comment]
Yes, right. Maybe basic format. 
Most used are bold and links.

**Comment by irrationalistic** [comment]
I've got this working, but the only question left is should completed or cancelled tasks also show the syntax highlighting for markdown.

(i'm using the afterglow-monokai syntax theme)

Plain ol' task:
![screen shot 2015-07-23 at 2 20 06 pm](https://cloud.githubusercontent.com/assets/851856/8861181/03e6f2a6-3146-11e5-9ff9-848bb8c2f227.png)

Completed with highlighting:
![screen shot 2015-07-23 at 2 21 49 pm](https://cloud.githubusercontent.com/assets/851856/8861209/30678408-3146-11e5-9646-021017c56f4d.png)

Completed without highlighting:
![screen shot 2015-07-23 at 2 23 00 pm](https://cloud.githubusercontent.com/assets/851856/8861243/769d45fc-3146-11e5-92d5-e0784b962058.png)

My vote is on removing highlighting upon complete/cancel, what are your thoughts?

**Comment by Ridermansb** [comment]
My vote is to removing :+1:

**Comment by mangecoeur** [comment]
Also keen to see markdown highlighting (also vote for removing highlighting on done tasks)

**Comment by irrationalistic** [comment]
I'll be posting the update as soon as I get a chance! I ran into some awkward issues with Atom's built-in markdown rendering reporting itself as `gfm` instead of `markdown` which also lead to some awkward styling decisions by many of the themes available. I'm not sure how to approach that bit, but my solution will work in the interim until a more clean plan is in place!
