### ISSUE TITLE
Overrides soft-wrap setting?

### ISSUE THREAD

**Issue by mangecoeur** [irrationalistic/atom-tasks#32]
I have the following in my config (also using the typewriter package to get a narrow centered editor column)

```cson
"source.gfm":
  editor:
    softWrap: true
"source.todo":
  editor:
    softWrap: true
```

However when I open a todo file it always has softWrap off and I have to manually toggle it on again, it's a bit annoying. I have no idea why though...

**Comment by mangecoeur** [comment]
Sorry, turns out I'm an idiot - you have to put `.source.todo` not `source.todo`...

**Comment by irrationalistic** [comment]
Glad you got it figured out!
