### ISSUE TITLE
Highlight URLs

### ISSUE THREAD

**Issue by andrelima** [irrationalistic/atom-tasks#35]
It would be really helpful if URLs were highlighted...

The standard `language-hyperlink` package already does this for text files, markdown files and comments. For example, by simply adding this to `styles.less`:

```
  .markup.underline.link.hyperlink {
    color: #04a6dc;
    text-decoration: underline;
  }
```

...URLs show up in blue, and underlined.  :)

Can we extend this functionality to atom-tasks' .todo / .taskpaper files?

**Comment by lnmunhoz** [comment]
Can you create a PR for this solution or explain how you did it? I want this feature too but I tried to change on `tasks.less` file on the package source and didn't work.

**Comment by andrelima** [comment]
@lnmunhoz This isn't the solution — it's a feature request. :)

I still don't know a lot about Atom, but I guess that the standard `language-hyperlink` package needs to add support for atom-tasks' .todo / .taskpaper files.

I really haven't got the time to pursue this further (for the foreseeable future) — Maybe you can request this at https://github.com/atom/language-hyperlink/issues ?

...Something like: "Add support for URLs in atom-tasks' .todo, .taskpaper files" for the title... You get the picture. ;)

Please let us know how it goes! Thanks!

**Comment by lnmunhoz** [comment]
Got it. Thank you!

**Comment by irrationalistic** [comment]
Hey guys! Thanks for exploring this.

Right now, the textual parts of each task are parsed additionally through the standard `gfm` language. This means that urls in the markdown format will receive proper highlighting. Of course, you are asking for normal urls to also be highlighted even if they are not in the markdown format. This should be doable, but I'll definitely look at the `language-hyperlink` package to see if there is anything we can borrow!

**Comment by andrelima** [comment]
> I'll definitely look at the `language-hyperlink` package to see if there is anything we can borrow!

Thanks, @irrationalistic for looking into this! And... ahem... for this whole package! ;)

**Comment by irrationalistic** [comment]
I'm running into a lot of bugs for a few of the other tasks as well. Seems something in a recent update got all confused with my local development of packages. Working through it, so i'll keep you posted.
