### ISSUE TITLE
Task markers get highlighted everywhere, not just at the beginning of lines

### ISSUE THREAD

**Issue by andrelima** [irrationalistic/atom-tasks#36]
I have `-` set as `baseMarker` and, currently, all `-` characters get treated as if they are task markers... The buffer's DOM gets changed with these semantics and so they're all highlighted.

I was able to fix this behavior by changing this part of `tasks/lib/tasks.cson` to become:

```
'repository':
  'marker':
    'match': '^\\s*(☐|✔|✘)'
    ...
```

...I believe this change should go into master, unless something is escaping me... Please let me know your thoughts on this...

Sorry that I'm not sending a pull request — I still gotta learn a bit more about how Git works!

**Comment by Zettt** [comment]
Thanks. Fixed it for me.

**Comment by andrelima** [comment]
I have now another fix so that `---` markdown text at beginning of line doesn't get highlighted too:

```
'repository':
  'marker':
    'match': '^\\s*(☐|✔|✘)\\s'
```

@Zettt You're welcome! — I'm glad it was worthwhile to share.  :)

**Comment by irrationalistic** [comment]
This seems valid to me! Thanks for exploring this :) I'll get it in as soon as I can.

**Comment by irrationalistic** [comment]
Unfortunately, this change seems to break the highlighting for completed and cancelled tasks. I'll need to do a bit more adjusting to fix this.

**Comment by irrationalistic** [comment]
I've found that it comes down to not being able to utilize the `^` in the repository marker section. For whatever reason that seems to be breaking the highlighting. I think it may be that previous rules are consuming the line start, so I'm going to see if I can work around this issue.

**Comment by andrelima** [comment]
Thank you!
