### ISSUE TITLE
Task separator 

### ISSUE THREAD

**Issue by tpoisot** [irrationalistic/atom-tasks#40]
The separator between archived and active tasks seems to be broken (on Linux, Fedora 22, up-to-date release of Atom). I tried with a couple different fonts, too.

![capture d ecran de 2015-09-07 18-47-33](https://cloud.githubusercontent.com/assets/579329/9723524/196665ac-5591-11e5-85fd-0bcc0f9a1c45.png)

**Comment by irrationalistic** [comment]
It's a UTF set of underscores. Fortunately there is a setting to adjust it! Try changing it to a series of actual underscores in the settings for the package and see if that helps. You'll have to delete the existing archive title and separator and re-archive the tasks for it to apply.

**Comment by tpoisot** [comment]
Works like a charm, :disappointed: for not having looked at the settings first....

**Comment by irrationalistic** [comment]
No worries! Glad it worked :)
