### ISSUE TITLE
Hotkey to insert a timestamp

### ISSUE THREAD

**Issue by girvo** [irrationalistic/atom-tasks#41]
Hey there, love the plugin!

A feature I'd absolutely love to have is a hotkey to insert a timestamp -- similar to the "done" or "cancel" commands. It'd just insert the current date/timestamp, perhaps with a `@log(<timestamp)` attribute. It helps me mark what I was working on and at what times for my timesheets afterwards, makes it a bit more flexible.

Thanks

**Comment by irrationalistic** [comment]
Great idea! Thanks :)

**Comment by irrationalistic** [comment]
I'm going to use `@timestamp(...)` to keep things clear. Let me know if you disagree!
