### ISSUE TITLE
todo.txt compatibility

### ISSUE THREAD

**Issue by orschiro** [irrationalistic/atom-tasks#43]
Dear @irrationalistic,

Thank you very much for this promising package! 

I have been looking for a way to completely manage my plain text file tasks in Atom. 

A question:

Is this package compatible with [todo.txt](https://www.todotxtpp.com/#)? Thus, can I sync the task list e.g. with my mobile phone?

Thankfully,

Robert

**Comment by irrationalistic** [comment]
Thanks, @orschiro! I haven't actually tested it with the app, so if you do end up trying this, i'd love to hear about any issues you have.

**Comment by irrationalistic** [comment]
I did a quick test on https://rawgit.com/bicarbon8/todoTxtWebUi/master/index.html, which is a web implementation of todo.txt. I imported one of the core files I use for testing the plugin and it didn't break, but there were some oddities.

![screen shot 2015-11-01 at 5 57 12 pm](https://cloud.githubusercontent.com/assets/851856/10872977/08779d5e-80c2-11e5-9a6f-635dfd8f9062.png)

It didn't seem to like the markers, which are pretty important to the way the plugin works. It also didn't like the format for the project lines either. It won't get you 100% parity, but it's close enough to work.

Would love to discuss this further if you have any ideas or thoughts on if/how supporting todo.txt can be done!

**Comment by orschiro** [comment]
Dear @irrationalistic,

Thanks for your testing! Currently I don't have any further suggestions to make. 

But this degree of compatibility is already sufficient for me. :) 

Warmly,

Robert

**Comment by irrationalistic** [comment]
Great! I am going to close this for now, but if you come across anything weird, please feel free to re-open! Thanks :)

**Comment by orschiro** [comment]
Will do, thanks again!  :)

~ Robert
