### ISSUE TITLE
base / cancelled / complete marker gets duplicates

### ISSUE THREAD

**Issue by dirk-thomas** [irrationalistic/atom-tasks#45]
When toggling the done / cancelled state repeatedly the marker gets duplicates over and over again.

Happens for me with Atom 1.1.0 and version 2.5.1 of this plugin (on Ubuntu Trusty).

**Comment by javs** [comment]
I can confirm, same versions on windows 7.

**Comment by shadaj** [comment]
This also appears for the same versions on OS X.

**Comment by irrationalistic** [comment]
Yikes! I'm seeing this as well. Will get to it as soon as I have time.

**Comment by irrationalistic** [comment]
It seems like the atom tokenizer has changed recently, which causes the code looking for line tokens to fail. I'll see what I can find out.

**Comment by irrationalistic** [comment]
Ok, I've got code down locally that seems to fix the issue. Had to remove the dependency on atom doing the line tokenization and do it manually. Will definitely need a cleanup later.

Writing the tests for the code then I'll be able to post the fix and release it.

**Comment by irrationalistic** [comment]
I put up a fix (tests were also broken, so that'll be a separate commit). Feel free to re-open this if the problem persists! If there are any new, unrelated bugs that come up from this change, please open them as separate issues! Thanks for your patience :)

**Comment by dirk-thomas** [comment]
I can confirm that it works correctly with version 2.6.0 for me. Thank you for the fix.
