### ISSUE TITLE
Theme support

### ISSUE THREAD

**Issue by ronilaukkarinen** [irrationalistic/atom-tasks#49]
Hi, first things first: thank you for this awesome package, I just recently moved from Sublime and I loved PlainTasks. I had a Markdown inspired theme for plaintasks called [plaintasks-markdown](https://github.com/ronilaukkarinen/plaintasks-markdown) and I was wondering is it possible to theme atom tasks? Thanks in advance.

**Comment by irrationalistic** [comment]
Thanks! And yes, this should definitely be possible. You could just modify your own editor stylesheet and target the different elements generated by this package. You could follow how things are set up here (https://github.com/irrationalistic/atom-tasks/blob/master/styles/tasks.less) and start changing out your own values. Let me know if you need some more specific help :)

**Comment by irrationalistic** [comment]
I'm going to mark this as closed. Feel free to re-open it if you were unable to achieve what you were hoping for!
