### ISSUE TITLE
Tab should advance bullet character

### ISSUE THREAD

**Issue by artusic** [irrationalistic/atom-tasks#56]
It would be nice if the tab key advanced the indentation of the whole item when the cursor is positioned past the bullet point.

My natural workflow for creating sub-items is to hit ctrl-enter to create the next bullet point, then hit tab to make it a sub-item. It's a little faster than doing enter / tab / ctrl-shift-L when typing fast.

Thanks! # # #

**Comment by irrationalistic** [comment]
You could probably do this as a custom keybinding. If you know the overall command you want to fire (probably, in this case, `editor:indent-selected-rows`), you could try this in your keybinding file:

```
'atom-text-editor:not(.mini)[data-grammar~="todo"]':
  'tab': 'editor:indent-selected-rows'
```

Same goes for `shift-tab`. It does mean that you can't use tab in the middle of a line, but that seems to be what you'd expect!

Does that help at all?

**Comment by artusic** [comment]
Ah, that's perfect, that gives me the exact behaviour I'm looking for!

Thanks a lot, and great work on the plug-in. I'm just getting into Atom and this plug-in was a big reason I was willing to give it a go.

**Comment by irrationalistic** [comment]
Awesome! That's great to hear :) Atom is super extensible, so you can do just about anything you want!
