### ISSUE TITLE
Project is no longer being included on completed task lines

### ISSUE THREAD

**Issue by haraldnagel** [irrationalistic/atom-tasks#58]
It appears that somewhere around the Atom 1.9.1 release, flagging a task as complete is not adding the `@project()` decoration to the line.

- Atom 1.9.1
- Tasks 2.6.0

Sample file format:
```
Project of awesome:
  - Do this thing
  ✔ Do the other thing @done(2016-08-03 10:30)
```

**Comment by irrationalistic** [comment]
I can reproduce this. Will look into it ASAP, thanks for flagging!

**Comment by irrationalistic** [comment]
Looks like `indentLevel` was removed as a property on tokenized lines, looking for a fix.

**Comment by irrationalistic** [comment]
Closing as this should be fixed now! Feel free to re-open if it crops back up :)

**Comment by haraldnagel** [comment]
:+1: works great. Thanks so much, this plug-in is very useful!

**Comment by massic80** [comment]
I'm having the same issue, four years later: I'm still in time to reopen it? :)
