### ISSUE TITLE
TextEditor.get is deprecated.

### ISSUE THREAD

**Issue by dirk-thomas** [irrationalistic/atom-tasks#63]
`TextEditor.prototype.displayBuffer` has always been private, but now
it is gone. Reading the `displayBuffer` property now returns a reference
to the containing `TextEditor`, which now provides *some* of the API of
the defunct `DisplayBuffer` class.
```
TextEditor.get (/opt/atom/resources/app.asar/src/text-editor.js:100:14)
status-bar-tasks.subscribeToActiveTextEditor (/home/dthomas/.atom/packages/tasks/lib/views/task-status-view.coffee:50:78)
status-bar-tasks.initialize (/home/dthomas/.atom/packages/tasks/lib/views/task-status-view.coffee:25:19)
Object.consumeStatusBar (/home/dthomas/.atom/packages/tasks/lib/tasks.coffee:189:23)
Provider.provide (/opt/atom/resources/app.asar/node_modules/service-hub/lib/provider.js:29:52)
ServiceHub.provide (/opt/atom/resources/app.asar/node_modules/service-hub/lib/service-hub.js:30:20)
```

**Comment by dirk-thomas** [comment]
Thank you for the quick update!

**Comment by benji1304** [comment]
@irrationalistic i'm still seeing this error on a fresh install of atom. Any ideas? 

`
TextEditor.prototype.displayBuffer has always been private, but now it is gone. Reading the displayBuffer property now returns a reference to the containing TextEditor, which now provides some of the API of the defunct DisplayBuffer class.
Report Issue
TextEditor.get - C:\Users\bstokes\AppData\Local\atom\app-1.13.1\resources\app.asar\src\text-editor.js:101:14
Object.getProjects - C:\Users\bstokes\.atom\packages\tasks\lib\tasksUtilities.coffee:216:21
<unknown> - C:\Users\bstokes\.atom\packages\tasks\lib\tasks.coffee:258:30
Array.map - native
<unknown> - C:\Users\bstokes\.atom\packages\tasks\lib\tasks.coffee:250:53
TextBuffer.transact - C:\Users\bstokes\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:867:18`

**Comment by irrationalistic** [comment]
I think I just missed the ones in the util! Will post an update asap.
