### ISSUE TITLE
Add separator snippet

### ISSUE THREAD

**Issue by nirfse** [irrationalistic/atom-tasks#64]
Hello, please consider adding single-line separator snippet. Coming from the Sublime Text's [PlainTasks](https://github.com/aziz/PlainTasks#usage), I find really useful to separate several *todo*-lists in a single file.

Just by typing `--` and pressing `Tab` you get:
```
--- ✄ -----------------------
```

**Comment by irrationalistic** [comment]
Are the tasks from separated lists all going into the same archive when closed?

**Comment by nirfse** [comment]
Hey @irrationalistic, if you going to implement this feature, tasks may be appended to the same archive as a more easier solution. However, personally I believe it would be better to split archive for each separated list in the file.

**Comment by nirfse** [comment]
Hey, closing this issue as irrelevant after many years.
