### ISSUE TITLE
CMD+d is not Completing tasks in my task list in atom

### ISSUE THREAD

**Issue by dmccullo** [irrationalistic/atom-tasks#65]
CMD+d does nothing and Right click and Complete Task on menu does nothing the box stays and no check marks appear.

file is name.todo
highlighting of titles works 
tasks all have boxes
tasks look like this
☐  asked for an update @timestamp(2017-01-04 14:20)

Any help would be appreciated...

**Comment by irrationalistic** [comment]
Could you turn on the hotkey visualizer with Packages > Keybinding Resolver > Toggle, then hit cmd-d on a task and attach a screenshot of the pane contents? It's probably colliding with another binding!

**Comment by dmccullo** [comment]
Sure here you go!
![atom-tasks ctrl-d issue](https://cloud.githubusercontent.com/assets/18235932/21686673/39d2c7be-d334-11e6-97ef-907bf61ad2b9.png)

**Comment by dmccullo** [comment]
And thanks for the quick response HEHE

**Comment by dmccullo** [comment]
YEAP!  i edited tasks.cson and changed it to 'cmd-shift-d': 'tasks:complete' now works great!
![atom-tasks cmd-d issue](https://cloud.githubusercontent.com/assets/18235932/21688086/8a72b24c-d339-11e6-886f-f54639d106fa.png)

**Comment by irrationalistic** [comment]
Haha, great!!
