### ISSUE TITLE
Bug with recognizing subprojects

### ISSUE THREAD

**Issue by sbaack** [irrationalistic/atom-tasks#69]
Thank you for this great package! I found a minor bug: I like to separate notes from tasks with new lines (it's just nicer to read on larger files). But when I do that, the Tasks package fails to recognize the current project as a sub-project. To illustrate:

1. Marking task from the subproject as done without new lines around note. The task gets correctly tagged as `@project(Main Project / Subproject)`:
<img width="666" alt="screen shot 2017-01-31 at 12 06 29 pm" src="https://cloud.githubusercontent.com/assets/8274140/22462649/7bd40496-e7ae-11e6-97be-b3470023ad72.png">

2. Doing the same, but with new lines to separate note. The task is now only tagged as `@project(Subproject)`:
<img width="542" alt="screen shot 2017-01-31 at 12 06 50 pm" src="https://cloud.githubusercontent.com/assets/8274140/22462700/af3f953e-e7ae-11e6-953a-3705cdea9f46.png">

The original Taskpaper app has no issues with new lines around notes:
<img width="514" alt="screen shot 2017-01-31 at 12 07 30 pm" src="https://cloud.githubusercontent.com/assets/8274140/22462857/52b85606-e7af-11e6-9023-f44d348a2484.png">

Again, thank you for your great work!

**Comment by irrationalistic** [comment]
This was an optimization so it wouldn't have to check forever, but let me see if I can get it to skip empty lines!
