### ISSUE TITLE
Automatically mark parent task as completed

### ISSUE THREAD

**Issue by garygreen** [irrationalistic/atom-tasks#71]
It would be cool if when you marked all subtasks as completed it'll mark the parent as completed, too.

![check parent](https://cloud.githubusercontent.com/assets/1702638/23360452/3cc6e60c-fce3-11e6-8188-f255bf0802a5.gif)

**Comment by irrationalistic** [comment]
What would happen if the user marked all the sub tasks as done and then unmarked one of the sub tasks? Would the parent task be re-opened? I'm a little bit worried about this being "surprising" UX so I want to make sure we discuss the cases!

**Comment by garygreen** [comment]
> What would happen if the user marked all the sub tasks as done and then unmarked one of the sub tasks? Would the parent task be re-opened?

Yes, since all the sub tasks are no longer all done. Same for toggling the parent - it should mark all sub tasks done / not done.

**Comment by irrationalistic** [comment]
I'm wondering now if "parent" tasks should have a different structure/icon. Right now projects are the ideal way to organize sub tasks, but your suggestions are really adding a ton of power to a nested task! I think this makes sense to implement, but it'll take a little testing to make sure it feels right. For instance, if you complete a task in the list, then complete the parent, then toggle the parent off, it will unmark that subtask too, which may be confusing, but also maybe not! I'll try to take a look at a potential implementation and see how it plays out :)

**Comment by ricpelo** [comment]
Yes, please! This is a must. [Checkvist](https://www.checkvist.com), for instance, does that and it's great.

**Comment by pabloaperezfernandez** [comment]
Was this closed because it was decided to not pursue/develop or because it got completed?  If completed, how to I get it to work on Github.  Org-mode in Emacs works like this, and it is very helpful.
